#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

# Ignore Shellcheck SC2086 for variable expansion in dig command
# shellcheck disable=SC2086

display_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    local destination

    if [[ -z $subdomain ]]; then
        subdomain_list=("www" "lb-01" "web-01" "web-02")
    else
        subdomain_list=("$subdomain")
    fi

    for sub in "${subdomain_list[@]}"; do
        query_output=$(dig +short "$sub.$domain")
        record_type=$(echo "$query_output" | awk '{print $2}')
        destination=$(echo "$query_output" | awk '{print $1}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

if [[ $# -eq 0 || $# -gt 2 ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

display_info "$1" "$2"
