#!/usr/bin/env bash
# This is the HAProxy configuration file for SSL termination

frontend www-http
    bind *:80
    reqadd X-Forwarded-Proto:\ http
    default_backend www-backend

frontend www-https
    bind *:443 ssl crt /etc/ssl/certs/your_domain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    server web-server 127.0.0.1:80
