#!/usr/bin/env bash

# Update package index
apt-get update

# Install nginx
apt-get install -y nginx

# Start nginx service
service nginx start

# Create default HTML page
echo "Hello World!" > /var/www/html/index.html

# Check if Nginx is listening on port 80
nc -z localhost 80

# If Nginx is listening, print "Hello World!" using curl
if [ $? -eq 0 ]; then
    curl -s 127.0.0.1
fi

exit 0
