#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page

# Create custom 404 error page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Update Nginx configuration to use the custom 404 page
echo "error_page 404 /404.html;" | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx server
service nginx restart
