#!/usr/bin/env bash
# this file that pings an IP address

# ip variable
IP="${1}"

# name variable
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
