#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80

# Remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default Nginx configuration file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx service
service nginx restart
