#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

# the IPs displayed may be different depending on which machine you are running the script on.
#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
